import { authClient } from "@/app/lib/auth/client";
import { NeonAuthUIProvider } from "@neondatabase/auth/react";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { StrictMode } from "react";
import { NextIntlClientProvider } from "next-intl";
import { Header } from "@/app/components/header";
import { Footer } from "@/app/components/footer";

const openSans = Open_Sans({
  variable: "--font-sans",
  subsets: ["cyrillic", "latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StrictMode>
      <NextIntlClientProvider>
        <NeonAuthUIProvider authClient={authClient} redirectTo="/admin" emailOTP>
          <html lang="en" className={openSans.variable} suppressHydrationWarning>
            <body className="antialiased">
              <Header />
              {children}
              <Footer />
            </body>
          </html>
        </NeonAuthUIProvider>
      </NextIntlClientProvider>
    </StrictMode>
  );
}
