import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { StrictMode } from "react";
import { NextIntlClientProvider } from "next-intl";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["cyrillic", "latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StrictMode>
      <NextIntlClientProvider>
        <html lang="en">
          <body className={`${openSans.variable} antialiased`}>{children}</body>
        </html>
      </NextIntlClientProvider>
    </StrictMode>
  );
}
