import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { StrictMode } from "react";
import { NextIntlClientProvider } from "next-intl";
import { Header } from "@/app/components/header";
import { Footer } from "@/app/components/footer";

const openSans = Open_Sans({
  variable: "--font-sans",
  subsets: ["cyrillic", "latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StrictMode>
      <NextIntlClientProvider>
        <html lang="en" className={openSans.variable}>
          <body className="antialiased">
            <Header />
            {children}
            <Footer />
          </body>
        </html>
      </NextIntlClientProvider>
    </StrictMode>
  );
}
